// api/generate.js
// Vercel Serverless Function to interact with Gemini API

export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    const API_KEY = process.env.GEMINI_API_KEY;
    
    if (!API_KEY) {
        return res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server.' });
    }

    try {
        // Extract data from frontend request
        const {
            jenjang, kelas, mapel, materi, tujuan,
            modelPembelajaran, jumlahSoal, kesulitan,
            bahasa, jenisSoal, p5, instruksi
        } = req.body;

        // Construct the prompt for Gemini
        const prompt = `
Anda adalah seorang ahli pendidikan dan kurikulum yang berpengalaman membuat Lembar Kerja Peserta Didik (LKPD) yang profesional, menarik, dan sesuai dengan standar pendidikan.

Buatlah sebuah LKPD dengan spesifikasi berikut:
- Jenjang & Kelas: ${jenjang} - ${kelas}
- Mata Pelajaran: ${mapel}
- Materi/Topik: ${materi}
- Tujuan Pembelajaran: ${tujuan}
- Model Pembelajaran: ${modelPembelajaran}
- Bahasa: ${bahasa}
- Elemen Profil Pelajar Pancasila (P5) yang disisipkan: ${p5.length > 0 ? p5.join(', ') : 'Tidak ada'}
- Jumlah Soal: ${jumlahSoal} soal
- Tingkat Kesulitan: ${kesulitan}
- Jenis Soal: ${jenisSoal.join(', ')}
${instruksi ? `- Instruksi Khusus: ${instruksi}` : ''}

Struktur LKPD yang harus Anda hasilkan (Gunakan format Markdown murni yang rapi, tanpa tag html):
1. Judul LKPD (Tarik, jelas)
2. Identitas (Nama Siswa, Kelas, No Absen)
3. Tujuan Pembelajaran
4. Petunjuk Belajar
5. Ringkasan Materi Singkat (Opsional, sesuai model pembelajaran)
6. Langkah-langkah Kegiatan (Sesuai dengan sintaks model pembelajaran ${modelPembelajaran})
7. Kumpulan Soal (Berjumlah ${jumlahSoal}, dibagi sesuai Jenis Soal yang dipilih, dan sesuai tingkat kesulitan ${kesulitan})
8. Nilai/Karakter P5 yang diharapkan

Gunakan bahasa yang profesional namun mudah dipahami oleh siswa kelas ${kelas}.
Pastikan format Markdown menggunakan heading (#, ##, ###), bold, dan list yang benar agar mudah dirender dan di-convert ke Microsoft Word.
        `;

        // Fetch to Google Gemini API REST Endpoint
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: prompt
                    }]
                }],
                generationConfig: {
                    temperature: 0.7,
                    topK: 40,
                    topP: 0.95,
                    maxOutputTokens: 8192,
                }
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error("Gemini API Error:", errorData);
            return res.status(500).json({ error: 'Failed to generate content from AI.' });
        }

        const data = await response.json();
        
        // Extract text from Gemini response
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!generatedText) {
            throw new Error("No text generated by AI");
        }

        // Return successful response to frontend
        return res.status(200).json({ result: generatedText });

    } catch (error) {
        console.error("Server Error:", error);
        return res.status(500).json({ error: 'Internal Server Error', message: error.message });
    }
}